# Generated by Django 3.1.7 on 2021-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210324_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(default='default-cover.jpg', upload_to='blog/articles/covers'),
        ),
    ]
