

from django import forms
from .models import Article 


class ArticleForm(forms.ModelForm):
    #---- method1 to create form --
    # title = forms.CharField()
    # body = forms.CharField(widget=forms.Textarea)
    # cover_photo = forms.ImageField()
    #---- method2 to create form  ArticleForm  inherits --  forms.ModelForm not forms.Form
    class Meta:
        model = Article
        fields = [
            "cover_photo",
            'title',
            'body',
            
        ]

    # notes created_at and updated_at generated by default by timestamp..ok
    #  after we create the form we import it in view.py to pass it to form.html to render it